name: 'market_sentinel'
version: '1.0.0'
config-version: 2

profile: 'market_sentinel'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  market_sentinel:
    staging:
      +materialized: view
    analytics:
      +materialized: view
